// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/isms/v1/dashboard.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 概览统计数据请求
type GetOverviewStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewStatsReq) Reset() {
	*x = GetOverviewStatsReq{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewStatsReq) ProtoMessage() {}

func (x *GetOverviewStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewStatsReq.ProtoReflect.Descriptor instead.
func (*GetOverviewStatsReq) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

// 概览统计数据响应
type GetOverviewStatsResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalSoftware    int64                  `protobuf:"varint,1,opt,name=total_software,json=totalSoftware,proto3" json:"total_software,omitempty"`            // 软件总数
	TotalDevelopers  int64                  `protobuf:"varint,2,opt,name=total_developers,json=totalDevelopers,proto3" json:"total_developers,omitempty"`      // 开发商总数
	TotalIndustries  int64                  `protobuf:"varint,3,opt,name=total_industries,json=totalIndustries,proto3" json:"total_industries,omitempty"`      // 行业总数
	TotalCountries   int64                  `protobuf:"varint,4,opt,name=total_countries,json=totalCountries,proto3" json:"total_countries,omitempty"`         // 国家总数
	NewSoftwareCount int64                  `protobuf:"varint,5,opt,name=new_software_count,json=newSoftwareCount,proto3" json:"new_software_count,omitempty"` // 新增软件数（最近30天）
	LastUpdated      int64                  `protobuf:"varint,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`                  // 最后更新时间（Unix时间戳）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOverviewStatsResp) Reset() {
	*x = GetOverviewStatsResp{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewStatsResp) ProtoMessage() {}

func (x *GetOverviewStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewStatsResp.ProtoReflect.Descriptor instead.
func (*GetOverviewStatsResp) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetOverviewStatsResp) GetTotalSoftware() int64 {
	if x != nil {
		return x.TotalSoftware
	}
	return 0
}

func (x *GetOverviewStatsResp) GetTotalDevelopers() int64 {
	if x != nil {
		return x.TotalDevelopers
	}
	return 0
}

func (x *GetOverviewStatsResp) GetTotalIndustries() int64 {
	if x != nil {
		return x.TotalIndustries
	}
	return 0
}

func (x *GetOverviewStatsResp) GetTotalCountries() int64 {
	if x != nil {
		return x.TotalCountries
	}
	return 0
}

func (x *GetOverviewStatsResp) GetNewSoftwareCount() int64 {
	if x != nil {
		return x.NewSoftwareCount
	}
	return 0
}

func (x *GetOverviewStatsResp) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

// 软件按行业分布统计请求
type GetSoftwareByIndustryStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopN          int32                  `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"` // 返回前N个行业，默认10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareByIndustryStatsReq) Reset() {
	*x = GetSoftwareByIndustryStatsReq{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareByIndustryStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareByIndustryStatsReq) ProtoMessage() {}

func (x *GetSoftwareByIndustryStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareByIndustryStatsReq.ProtoReflect.Descriptor instead.
func (*GetSoftwareByIndustryStatsReq) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetSoftwareByIndustryStatsReq) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

// 行业统计项
type IndustryStatItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndustryId    int32                  `protobuf:"varint,1,opt,name=industry_id,json=industryId,proto3" json:"industry_id,omitempty"`          // 行业ID
	IndustryName  string                 `protobuf:"bytes,2,opt,name=industry_name,json=industryName,proto3" json:"industry_name,omitempty"`     // 行业名称
	SoftwareCount int64                  `protobuf:"varint,3,opt,name=software_count,json=softwareCount,proto3" json:"software_count,omitempty"` // 软件数量
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`                           // 占比（百分比）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndustryStatItem) Reset() {
	*x = IndustryStatItem{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndustryStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndustryStatItem) ProtoMessage() {}

func (x *IndustryStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndustryStatItem.ProtoReflect.Descriptor instead.
func (*IndustryStatItem) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *IndustryStatItem) GetIndustryId() int32 {
	if x != nil {
		return x.IndustryId
	}
	return 0
}

func (x *IndustryStatItem) GetIndustryName() string {
	if x != nil {
		return x.IndustryName
	}
	return ""
}

func (x *IndustryStatItem) GetSoftwareCount() int64 {
	if x != nil {
		return x.SoftwareCount
	}
	return 0
}

func (x *IndustryStatItem) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// 软件按行业分布统计响应
type GetSoftwareByIndustryStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*IndustryStatItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 行业统计列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareByIndustryStatsResp) Reset() {
	*x = GetSoftwareByIndustryStatsResp{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareByIndustryStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareByIndustryStatsResp) ProtoMessage() {}

func (x *GetSoftwareByIndustryStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareByIndustryStatsResp.ProtoReflect.Descriptor instead.
func (*GetSoftwareByIndustryStatsResp) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetSoftwareByIndustryStatsResp) GetItems() []*IndustryStatItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 软件按国家分布统计请求
type GetSoftwareByCountryStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopN          int32                  `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"` // 返回前N个国家，默认10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareByCountryStatsReq) Reset() {
	*x = GetSoftwareByCountryStatsReq{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareByCountryStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareByCountryStatsReq) ProtoMessage() {}

func (x *GetSoftwareByCountryStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareByCountryStatsReq.ProtoReflect.Descriptor instead.
func (*GetSoftwareByCountryStatsReq) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *GetSoftwareByCountryStatsReq) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

// 国家统计项
type CountryStatItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryId     int32                  `protobuf:"varint,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`              // 国家ID
	CountryNameZh string                 `protobuf:"bytes,2,opt,name=country_name_zh,json=countryNameZh,proto3" json:"country_name_zh,omitempty"` // 国家中文名称
	CountryNameEn string                 `protobuf:"bytes,3,opt,name=country_name_en,json=countryNameEn,proto3" json:"country_name_en,omitempty"` // 国家英文名称
	SoftwareCount int64                  `protobuf:"varint,4,opt,name=software_count,json=softwareCount,proto3" json:"software_count,omitempty"`  // 软件数量
	Percentage    float64                `protobuf:"fixed64,5,opt,name=percentage,proto3" json:"percentage,omitempty"`                            // 占比（百分比）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryStatItem) Reset() {
	*x = CountryStatItem{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryStatItem) ProtoMessage() {}

func (x *CountryStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryStatItem.ProtoReflect.Descriptor instead.
func (*CountryStatItem) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *CountryStatItem) GetCountryId() int32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *CountryStatItem) GetCountryNameZh() string {
	if x != nil {
		return x.CountryNameZh
	}
	return ""
}

func (x *CountryStatItem) GetCountryNameEn() string {
	if x != nil {
		return x.CountryNameEn
	}
	return ""
}

func (x *CountryStatItem) GetSoftwareCount() int64 {
	if x != nil {
		return x.SoftwareCount
	}
	return 0
}

func (x *CountryStatItem) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// 软件按国家分布统计响应
type GetSoftwareByCountryStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CountryStatItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 国家统计列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareByCountryStatsResp) Reset() {
	*x = GetSoftwareByCountryStatsResp{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareByCountryStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareByCountryStatsResp) ProtoMessage() {}

func (x *GetSoftwareByCountryStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareByCountryStatsResp.ProtoReflect.Descriptor instead.
func (*GetSoftwareByCountryStatsResp) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *GetSoftwareByCountryStatsResp) GetItems() []*CountryStatItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 软件按开发商分布统计请求
type GetSoftwareByDeveloperStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopN          int32                  `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"` // 返回前N个开发商，默认10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareByDeveloperStatsReq) Reset() {
	*x = GetSoftwareByDeveloperStatsReq{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareByDeveloperStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareByDeveloperStatsReq) ProtoMessage() {}

func (x *GetSoftwareByDeveloperStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareByDeveloperStatsReq.ProtoReflect.Descriptor instead.
func (*GetSoftwareByDeveloperStatsReq) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *GetSoftwareByDeveloperStatsReq) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

// 开发商统计项
type DeveloperStatItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeveloperId     int32                  `protobuf:"varint,1,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`              // 开发商ID
	DeveloperNameZh string                 `protobuf:"bytes,2,opt,name=developer_name_zh,json=developerNameZh,proto3" json:"developer_name_zh,omitempty"` // 开发商中文名称
	DeveloperNameEn string                 `protobuf:"bytes,3,opt,name=developer_name_en,json=developerNameEn,proto3" json:"developer_name_en,omitempty"` // 开发商英文名称
	SoftwareCount   int64                  `protobuf:"varint,4,opt,name=software_count,json=softwareCount,proto3" json:"software_count,omitempty"`        // 软件数量
	Percentage      float64                `protobuf:"fixed64,5,opt,name=percentage,proto3" json:"percentage,omitempty"`                                  // 占比（百分比）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeveloperStatItem) Reset() {
	*x = DeveloperStatItem{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeveloperStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeveloperStatItem) ProtoMessage() {}

func (x *DeveloperStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeveloperStatItem.ProtoReflect.Descriptor instead.
func (*DeveloperStatItem) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *DeveloperStatItem) GetDeveloperId() int32 {
	if x != nil {
		return x.DeveloperId
	}
	return 0
}

func (x *DeveloperStatItem) GetDeveloperNameZh() string {
	if x != nil {
		return x.DeveloperNameZh
	}
	return ""
}

func (x *DeveloperStatItem) GetDeveloperNameEn() string {
	if x != nil {
		return x.DeveloperNameEn
	}
	return ""
}

func (x *DeveloperStatItem) GetSoftwareCount() int64 {
	if x != nil {
		return x.SoftwareCount
	}
	return 0
}

func (x *DeveloperStatItem) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// 软件按开发商分布统计响应
type GetSoftwareByDeveloperStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DeveloperStatItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 开发商统计列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareByDeveloperStatsResp) Reset() {
	*x = GetSoftwareByDeveloperStatsResp{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareByDeveloperStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareByDeveloperStatsResp) ProtoMessage() {}

func (x *GetSoftwareByDeveloperStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareByDeveloperStatsResp.ProtoReflect.Descriptor instead.
func (*GetSoftwareByDeveloperStatsResp) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *GetSoftwareByDeveloperStatsResp) GetItems() []*DeveloperStatItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 软件按年份发布趋势统计请求
type GetSoftwareTrendStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecentYears   int32                  `protobuf:"varint,1,opt,name=recent_years,json=recentYears,proto3" json:"recent_years,omitempty"` // 最近N年数据，默认5年
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareTrendStatsReq) Reset() {
	*x = GetSoftwareTrendStatsReq{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareTrendStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareTrendStatsReq) ProtoMessage() {}

func (x *GetSoftwareTrendStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareTrendStatsReq.ProtoReflect.Descriptor instead.
func (*GetSoftwareTrendStatsReq) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{11}
}

func (x *GetSoftwareTrendStatsReq) GetRecentYears() int32 {
	if x != nil {
		return x.RecentYears
	}
	return 0
}

// 年份趋势统计项
type TrendStatItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`                                        // 年份
	SoftwareCount int64                  `protobuf:"varint,2,opt,name=software_count,json=softwareCount,proto3" json:"software_count,omitempty"` // 软件数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendStatItem) Reset() {
	*x = TrendStatItem{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendStatItem) ProtoMessage() {}

func (x *TrendStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendStatItem.ProtoReflect.Descriptor instead.
func (*TrendStatItem) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{12}
}

func (x *TrendStatItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *TrendStatItem) GetSoftwareCount() int64 {
	if x != nil {
		return x.SoftwareCount
	}
	return 0
}

// 软件按年份发布趋势统计响应
type GetSoftwareTrendStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TrendStatItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 趋势统计列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareTrendStatsResp) Reset() {
	*x = GetSoftwareTrendStatsResp{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareTrendStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareTrendStatsResp) ProtoMessage() {}

func (x *GetSoftwareTrendStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareTrendStatsResp.ProtoReflect.Descriptor instead.
func (*GetSoftwareTrendStatsResp) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{13}
}

func (x *GetSoftwareTrendStatsResp) GetItems() []*TrendStatItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 软件按状态分布统计请求
type GetSoftwareByStatusStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareByStatusStatsReq) Reset() {
	*x = GetSoftwareByStatusStatsReq{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareByStatusStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareByStatusStatsReq) ProtoMessage() {}

func (x *GetSoftwareByStatusStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareByStatusStatsReq.ProtoReflect.Descriptor instead.
func (*GetSoftwareByStatusStatsReq) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{14}
}

// 状态统计项
type StatusStatItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态值
	StatusLabel   string                 `protobuf:"bytes,2,opt,name=status_label,json=statusLabel,proto3" json:"status_label,omitempty"`        // 状态标签
	SoftwareCount int64                  `protobuf:"varint,3,opt,name=software_count,json=softwareCount,proto3" json:"software_count,omitempty"` // 软件数量
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`                           // 占比（百分比）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusStatItem) Reset() {
	*x = StatusStatItem{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusStatItem) ProtoMessage() {}

func (x *StatusStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusStatItem.ProtoReflect.Descriptor instead.
func (*StatusStatItem) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{15}
}

func (x *StatusStatItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusStatItem) GetStatusLabel() string {
	if x != nil {
		return x.StatusLabel
	}
	return ""
}

func (x *StatusStatItem) GetSoftwareCount() int64 {
	if x != nil {
		return x.SoftwareCount
	}
	return 0
}

func (x *StatusStatItem) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// 软件按状态分布统计响应
type GetSoftwareByStatusStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StatusStatItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 状态统计列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSoftwareByStatusStatsResp) Reset() {
	*x = GetSoftwareByStatusStatsResp{}
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSoftwareByStatusStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareByStatusStatsResp) ProtoMessage() {}

func (x *GetSoftwareByStatusStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_isms_v1_dashboard_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareByStatusStatsResp.ProtoReflect.Descriptor instead.
func (*GetSoftwareByStatusStatsResp) Descriptor() ([]byte, []int) {
	return file_api_isms_v1_dashboard_proto_rawDescGZIP(), []int{16}
}

func (x *GetSoftwareByStatusStatsResp) GetItems() []*StatusStatItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_isms_v1_dashboard_proto protoreflect.FileDescriptor

const file_api_isms_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/isms/v1/dashboard.proto\x12\aisms.v1\x1a\x1cgoogle/api/annotations.proto\"\x15\n" +
	"\x13GetOverviewStatsReq\"\x8d\x02\n" +
	"\x14GetOverviewStatsResp\x12%\n" +
	"\x0etotal_software\x18\x01 \x01(\x03R\rtotalSoftware\x12)\n" +
	"\x10total_developers\x18\x02 \x01(\x03R\x0ftotalDevelopers\x12)\n" +
	"\x10total_industries\x18\x03 \x01(\x03R\x0ftotalIndustries\x12'\n" +
	"\x0ftotal_countries\x18\x04 \x01(\x03R\x0etotalCountries\x12,\n" +
	"\x12new_software_count\x18\x05 \x01(\x03R\x10newSoftwareCount\x12!\n" +
	"\flast_updated\x18\x06 \x01(\x03R\vlastUpdated\"4\n" +
	"\x1dGetSoftwareByIndustryStatsReq\x12\x13\n" +
	"\x05top_n\x18\x01 \x01(\x05R\x04topN\"\x9f\x01\n" +
	"\x10IndustryStatItem\x12\x1f\n" +
	"\vindustry_id\x18\x01 \x01(\x05R\n" +
	"industryId\x12#\n" +
	"\rindustry_name\x18\x02 \x01(\tR\findustryName\x12%\n" +
	"\x0esoftware_count\x18\x03 \x01(\x03R\rsoftwareCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\"Q\n" +
	"\x1eGetSoftwareByIndustryStatsResp\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.isms.v1.IndustryStatItemR\x05items\"3\n" +
	"\x1cGetSoftwareByCountryStatsReq\x12\x13\n" +
	"\x05top_n\x18\x01 \x01(\x05R\x04topN\"\xc7\x01\n" +
	"\x0fCountryStatItem\x12\x1d\n" +
	"\n" +
	"country_id\x18\x01 \x01(\x05R\tcountryId\x12&\n" +
	"\x0fcountry_name_zh\x18\x02 \x01(\tR\rcountryNameZh\x12&\n" +
	"\x0fcountry_name_en\x18\x03 \x01(\tR\rcountryNameEn\x12%\n" +
	"\x0esoftware_count\x18\x04 \x01(\x03R\rsoftwareCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x01R\n" +
	"percentage\"O\n" +
	"\x1dGetSoftwareByCountryStatsResp\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.isms.v1.CountryStatItemR\x05items\"5\n" +
	"\x1eGetSoftwareByDeveloperStatsReq\x12\x13\n" +
	"\x05top_n\x18\x01 \x01(\x05R\x04topN\"\xd5\x01\n" +
	"\x11DeveloperStatItem\x12!\n" +
	"\fdeveloper_id\x18\x01 \x01(\x05R\vdeveloperId\x12*\n" +
	"\x11developer_name_zh\x18\x02 \x01(\tR\x0fdeveloperNameZh\x12*\n" +
	"\x11developer_name_en\x18\x03 \x01(\tR\x0fdeveloperNameEn\x12%\n" +
	"\x0esoftware_count\x18\x04 \x01(\x03R\rsoftwareCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x01R\n" +
	"percentage\"S\n" +
	"\x1fGetSoftwareByDeveloperStatsResp\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.isms.v1.DeveloperStatItemR\x05items\"=\n" +
	"\x18GetSoftwareTrendStatsReq\x12!\n" +
	"\frecent_years\x18\x01 \x01(\x05R\vrecentYears\"J\n" +
	"\rTrendStatItem\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12%\n" +
	"\x0esoftware_count\x18\x02 \x01(\x03R\rsoftwareCount\"I\n" +
	"\x19GetSoftwareTrendStatsResp\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.isms.v1.TrendStatItemR\x05items\"\x1d\n" +
	"\x1bGetSoftwareByStatusStatsReq\"\x92\x01\n" +
	"\x0eStatusStatItem\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fstatus_label\x18\x02 \x01(\tR\vstatusLabel\x12%\n" +
	"\x0esoftware_count\x18\x03 \x01(\x03R\rsoftwareCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\"M\n" +
	"\x1cGetSoftwareByStatusStatsResp\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.isms.v1.StatusStatItemR\x05items2\xeb\x06\n" +
	"\tDashboard\x12o\n" +
	"\x10GetOverviewStats\x12\x1c.isms.v1.GetOverviewStatsReq\x1a\x1d.isms.v1.GetOverviewStatsResp\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/dashboard/overview\x12\x99\x01\n" +
	"\x1aGetSoftwareByIndustryStats\x12&.isms.v1.GetSoftwareByIndustryStatsReq\x1a'.isms.v1.GetSoftwareByIndustryStatsResp\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/dashboard/software-by-industry\x12\x95\x01\n" +
	"\x19GetSoftwareByCountryStats\x12%.isms.v1.GetSoftwareByCountryStatsReq\x1a&.isms.v1.GetSoftwareByCountryStatsResp\")\x82\xd3\xe4\x93\x02#\x12!/v1/dashboard/software-by-country\x12\x9d\x01\n" +
	"\x1bGetSoftwareByDeveloperStats\x12'.isms.v1.GetSoftwareByDeveloperStatsReq\x1a(.isms.v1.GetSoftwareByDeveloperStatsResp\"+\x82\xd3\xe4\x93\x02%\x12#/v1/dashboard/software-by-developer\x12\x84\x01\n" +
	"\x15GetSoftwareTrendStats\x12!.isms.v1.GetSoftwareTrendStatsReq\x1a\".isms.v1.GetSoftwareTrendStatsResp\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/dashboard/software-trend\x12\x91\x01\n" +
	"\x18GetSoftwareByStatusStats\x12$.isms.v1.GetSoftwareByStatusStatsReq\x1a%.isms.v1.GetSoftwareByStatusStatsResp\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/dashboard/software-by-statusB\x15Z\x13isms/api/isms/v1;v1b\x06proto3"

var (
	file_api_isms_v1_dashboard_proto_rawDescOnce sync.Once
	file_api_isms_v1_dashboard_proto_rawDescData []byte
)

func file_api_isms_v1_dashboard_proto_rawDescGZIP() []byte {
	file_api_isms_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_api_isms_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_isms_v1_dashboard_proto_rawDesc), len(file_api_isms_v1_dashboard_proto_rawDesc)))
	})
	return file_api_isms_v1_dashboard_proto_rawDescData
}

var file_api_isms_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_isms_v1_dashboard_proto_goTypes = []any{
	(*GetOverviewStatsReq)(nil),             // 0: isms.v1.GetOverviewStatsReq
	(*GetOverviewStatsResp)(nil),            // 1: isms.v1.GetOverviewStatsResp
	(*GetSoftwareByIndustryStatsReq)(nil),   // 2: isms.v1.GetSoftwareByIndustryStatsReq
	(*IndustryStatItem)(nil),                // 3: isms.v1.IndustryStatItem
	(*GetSoftwareByIndustryStatsResp)(nil),  // 4: isms.v1.GetSoftwareByIndustryStatsResp
	(*GetSoftwareByCountryStatsReq)(nil),    // 5: isms.v1.GetSoftwareByCountryStatsReq
	(*CountryStatItem)(nil),                 // 6: isms.v1.CountryStatItem
	(*GetSoftwareByCountryStatsResp)(nil),   // 7: isms.v1.GetSoftwareByCountryStatsResp
	(*GetSoftwareByDeveloperStatsReq)(nil),  // 8: isms.v1.GetSoftwareByDeveloperStatsReq
	(*DeveloperStatItem)(nil),               // 9: isms.v1.DeveloperStatItem
	(*GetSoftwareByDeveloperStatsResp)(nil), // 10: isms.v1.GetSoftwareByDeveloperStatsResp
	(*GetSoftwareTrendStatsReq)(nil),        // 11: isms.v1.GetSoftwareTrendStatsReq
	(*TrendStatItem)(nil),                   // 12: isms.v1.TrendStatItem
	(*GetSoftwareTrendStatsResp)(nil),       // 13: isms.v1.GetSoftwareTrendStatsResp
	(*GetSoftwareByStatusStatsReq)(nil),     // 14: isms.v1.GetSoftwareByStatusStatsReq
	(*StatusStatItem)(nil),                  // 15: isms.v1.StatusStatItem
	(*GetSoftwareByStatusStatsResp)(nil),    // 16: isms.v1.GetSoftwareByStatusStatsResp
}
var file_api_isms_v1_dashboard_proto_depIdxs = []int32{
	3,  // 0: isms.v1.GetSoftwareByIndustryStatsResp.items:type_name -> isms.v1.IndustryStatItem
	6,  // 1: isms.v1.GetSoftwareByCountryStatsResp.items:type_name -> isms.v1.CountryStatItem
	9,  // 2: isms.v1.GetSoftwareByDeveloperStatsResp.items:type_name -> isms.v1.DeveloperStatItem
	12, // 3: isms.v1.GetSoftwareTrendStatsResp.items:type_name -> isms.v1.TrendStatItem
	15, // 4: isms.v1.GetSoftwareByStatusStatsResp.items:type_name -> isms.v1.StatusStatItem
	0,  // 5: isms.v1.Dashboard.GetOverviewStats:input_type -> isms.v1.GetOverviewStatsReq
	2,  // 6: isms.v1.Dashboard.GetSoftwareByIndustryStats:input_type -> isms.v1.GetSoftwareByIndustryStatsReq
	5,  // 7: isms.v1.Dashboard.GetSoftwareByCountryStats:input_type -> isms.v1.GetSoftwareByCountryStatsReq
	8,  // 8: isms.v1.Dashboard.GetSoftwareByDeveloperStats:input_type -> isms.v1.GetSoftwareByDeveloperStatsReq
	11, // 9: isms.v1.Dashboard.GetSoftwareTrendStats:input_type -> isms.v1.GetSoftwareTrendStatsReq
	14, // 10: isms.v1.Dashboard.GetSoftwareByStatusStats:input_type -> isms.v1.GetSoftwareByStatusStatsReq
	1,  // 11: isms.v1.Dashboard.GetOverviewStats:output_type -> isms.v1.GetOverviewStatsResp
	4,  // 12: isms.v1.Dashboard.GetSoftwareByIndustryStats:output_type -> isms.v1.GetSoftwareByIndustryStatsResp
	7,  // 13: isms.v1.Dashboard.GetSoftwareByCountryStats:output_type -> isms.v1.GetSoftwareByCountryStatsResp
	10, // 14: isms.v1.Dashboard.GetSoftwareByDeveloperStats:output_type -> isms.v1.GetSoftwareByDeveloperStatsResp
	13, // 15: isms.v1.Dashboard.GetSoftwareTrendStats:output_type -> isms.v1.GetSoftwareTrendStatsResp
	16, // 16: isms.v1.Dashboard.GetSoftwareByStatusStats:output_type -> isms.v1.GetSoftwareByStatusStatsResp
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_isms_v1_dashboard_proto_init() }
func file_api_isms_v1_dashboard_proto_init() {
	if File_api_isms_v1_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_isms_v1_dashboard_proto_rawDesc), len(file_api_isms_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_isms_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_api_isms_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_api_isms_v1_dashboard_proto_msgTypes,
	}.Build()
	File_api_isms_v1_dashboard_proto = out.File
	file_api_isms_v1_dashboard_proto_goTypes = nil
	file_api_isms_v1_dashboard_proto_depIdxs = nil
}
