// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: isms/v1/industry.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 根据大类查询小类的请求
type GetSubcategoriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryCode  string                 `protobuf:"bytes,1,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"` // 大类代码（如B、C）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubcategoriesReq) Reset() {
	*x = GetSubcategoriesReq{}
	mi := &file_isms_v1_industry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubcategoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubcategoriesReq) ProtoMessage() {}

func (x *GetSubcategoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_isms_v1_industry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubcategoriesReq.ProtoReflect.Descriptor instead.
func (*GetSubcategoriesReq) Descriptor() ([]byte, []int) {
	return file_isms_v1_industry_proto_rawDescGZIP(), []int{0}
}

func (x *GetSubcategoriesReq) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

// 查询结果
type GetSubcategoriesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subcategories []*IsmsIndustry        `protobuf:"bytes,1,rep,name=subcategories,proto3" json:"subcategories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubcategoriesResp) Reset() {
	*x = GetSubcategoriesResp{}
	mi := &file_isms_v1_industry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubcategoriesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubcategoriesResp) ProtoMessage() {}

func (x *GetSubcategoriesResp) ProtoReflect() protoreflect.Message {
	mi := &file_isms_v1_industry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubcategoriesResp.ProtoReflect.Descriptor instead.
func (*GetSubcategoriesResp) Descriptor() ([]byte, []int) {
	return file_isms_v1_industry_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubcategoriesResp) GetSubcategories() []*IsmsIndustry {
	if x != nil {
		return x.Subcategories
	}
	return nil
}

// 查询所有大类的请求
type ListCategoriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesReq) Reset() {
	*x = ListCategoriesReq{}
	mi := &file_isms_v1_industry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesReq) ProtoMessage() {}

func (x *ListCategoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_isms_v1_industry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesReq.ProtoReflect.Descriptor instead.
func (*ListCategoriesReq) Descriptor() ([]byte, []int) {
	return file_isms_v1_industry_proto_rawDescGZIP(), []int{2}
}

// 所有大类的查询结果
type ListCategoriesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*IndustryCategory    `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResp) Reset() {
	*x = ListCategoriesResp{}
	mi := &file_isms_v1_industry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResp) ProtoMessage() {}

func (x *ListCategoriesResp) ProtoReflect() protoreflect.Message {
	mi := &file_isms_v1_industry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResp.ProtoReflect.Descriptor instead.
func (*ListCategoriesResp) Descriptor() ([]byte, []int) {
	return file_isms_v1_industry_proto_rawDescGZIP(), []int{3}
}

func (x *ListCategoriesResp) GetCategories() []*IndustryCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

// 行业分类结构体
type IsmsIndustry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryCode    string                 `protobuf:"bytes,2,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	CategoryName    string                 `protobuf:"bytes,3,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	SubcategoryCode string                 `protobuf:"bytes,4,opt,name=subcategory_code,json=subcategoryCode,proto3" json:"subcategory_code,omitempty"`
	SubcategoryName string                 `protobuf:"bytes,5,opt,name=subcategory_name,json=subcategoryName,proto3" json:"subcategory_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IsmsIndustry) Reset() {
	*x = IsmsIndustry{}
	mi := &file_isms_v1_industry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsmsIndustry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsmsIndustry) ProtoMessage() {}

func (x *IsmsIndustry) ProtoReflect() protoreflect.Message {
	mi := &file_isms_v1_industry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsmsIndustry.ProtoReflect.Descriptor instead.
func (*IsmsIndustry) Descriptor() ([]byte, []int) {
	return file_isms_v1_industry_proto_rawDescGZIP(), []int{4}
}

func (x *IsmsIndustry) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IsmsIndustry) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *IsmsIndustry) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *IsmsIndustry) GetSubcategoryCode() string {
	if x != nil {
		return x.SubcategoryCode
	}
	return ""
}

func (x *IsmsIndustry) GetSubcategoryName() string {
	if x != nil {
		return x.SubcategoryName
	}
	return ""
}

// 大类信息
type IndustryCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryCode  string                 `protobuf:"bytes,1,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndustryCategory) Reset() {
	*x = IndustryCategory{}
	mi := &file_isms_v1_industry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndustryCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndustryCategory) ProtoMessage() {}

func (x *IndustryCategory) ProtoReflect() protoreflect.Message {
	mi := &file_isms_v1_industry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndustryCategory.ProtoReflect.Descriptor instead.
func (*IndustryCategory) Descriptor() ([]byte, []int) {
	return file_isms_v1_industry_proto_rawDescGZIP(), []int{5}
}

func (x *IndustryCategory) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *IndustryCategory) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

var File_isms_v1_industry_proto protoreflect.FileDescriptor

const file_isms_v1_industry_proto_rawDesc = "" +
	"\n" +
	"\x16isms/v1/industry.proto\x12\aisms.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"E\n" +
	"\x13GetSubcategoriesReq\x12.\n" +
	"\rcategory_code\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x02R\fcategoryCode\"S\n" +
	"\x14GetSubcategoriesResp\x12;\n" +
	"\rsubcategories\x18\x01 \x03(\v2\x15.isms.v1.IsmsIndustryR\rsubcategories\"\x13\n" +
	"\x11ListCategoriesReq\"O\n" +
	"\x12ListCategoriesResp\x129\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x19.isms.v1.IndustryCategoryR\n" +
	"categories\"\xbe\x01\n" +
	"\fIsmsIndustry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\rcategory_code\x18\x02 \x01(\tR\fcategoryCode\x12#\n" +
	"\rcategory_name\x18\x03 \x01(\tR\fcategoryName\x12)\n" +
	"\x10subcategory_code\x18\x04 \x01(\tR\x0fsubcategoryCode\x12)\n" +
	"\x10subcategory_name\x18\x05 \x01(\tR\x0fsubcategoryName\"\\\n" +
	"\x10IndustryCategory\x12#\n" +
	"\rcategory_code\x18\x01 \x01(\tR\fcategoryCode\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName2\xf5\x01\n" +
	"\bIndustry\x12\x85\x01\n" +
	"\x10GetSubcategories\x12\x1c.isms.v1.GetSubcategoriesReq\x1a\x1d.isms.v1.GetSubcategoriesResp\"4\x82\xd3\xe4\x93\x02.\x12,/v1/categories/{category_code}/subcategories\x12a\n" +
	"\x0eListCategories\x12\x1a.isms.v1.ListCategoriesReq\x1a\x1b.isms.v1.ListCategoriesResp\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categoriesB\x15Z\x13isms/api/isms/v1;v1b\x06proto3"

var (
	file_isms_v1_industry_proto_rawDescOnce sync.Once
	file_isms_v1_industry_proto_rawDescData []byte
)

func file_isms_v1_industry_proto_rawDescGZIP() []byte {
	file_isms_v1_industry_proto_rawDescOnce.Do(func() {
		file_isms_v1_industry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_isms_v1_industry_proto_rawDesc), len(file_isms_v1_industry_proto_rawDesc)))
	})
	return file_isms_v1_industry_proto_rawDescData
}

var file_isms_v1_industry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_isms_v1_industry_proto_goTypes = []any{
	(*GetSubcategoriesReq)(nil),  // 0: isms.v1.GetSubcategoriesReq
	(*GetSubcategoriesResp)(nil), // 1: isms.v1.GetSubcategoriesResp
	(*ListCategoriesReq)(nil),    // 2: isms.v1.ListCategoriesReq
	(*ListCategoriesResp)(nil),   // 3: isms.v1.ListCategoriesResp
	(*IsmsIndustry)(nil),         // 4: isms.v1.IsmsIndustry
	(*IndustryCategory)(nil),     // 5: isms.v1.IndustryCategory
}
var file_isms_v1_industry_proto_depIdxs = []int32{
	4, // 0: isms.v1.GetSubcategoriesResp.subcategories:type_name -> isms.v1.IsmsIndustry
	5, // 1: isms.v1.ListCategoriesResp.categories:type_name -> isms.v1.IndustryCategory
	0, // 2: isms.v1.Industry.GetSubcategories:input_type -> isms.v1.GetSubcategoriesReq
	2, // 3: isms.v1.Industry.ListCategories:input_type -> isms.v1.ListCategoriesReq
	1, // 4: isms.v1.Industry.GetSubcategories:output_type -> isms.v1.GetSubcategoriesResp
	3, // 5: isms.v1.Industry.ListCategories:output_type -> isms.v1.ListCategoriesResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_isms_v1_industry_proto_init() }
func file_isms_v1_industry_proto_init() {
	if File_isms_v1_industry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_isms_v1_industry_proto_rawDesc), len(file_isms_v1_industry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_isms_v1_industry_proto_goTypes,
		DependencyIndexes: file_isms_v1_industry_proto_depIdxs,
		MessageInfos:      file_isms_v1_industry_proto_msgTypes,
	}.Build()
	File_isms_v1_industry_proto = out.File
	file_isms_v1_industry_proto_goTypes = nil
	file_isms_v1_industry_proto_depIdxs = nil
}
