// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameIsmsSoftwareIndustry = "isms_software_industry"

// IsmsSoftwareIndustry 软件与行业多对多关联表
type IsmsSoftwareIndustry struct {
	SoftwareID int32     `gorm:"column:software_id;type:int(10) unsigned;primaryKey;comment:软件ID（关联isms_software.id）" json:"software_id"`                                   // 软件ID（关联isms_software.id）
	IndustryID int32     `gorm:"column:industry_id;type:smallint(5) unsigned;primaryKey;index:idx_industry,priority:1;comment:行业ID（关联isms_industry.id）" json:"industry_id"` // 行业ID（关联isms_industry.id）
	CreatedAt  time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:关联创建时间" json:"created_at"`                                       // 关联创建时间
}

// TableName IsmsSoftwareIndustry's table name
func (*IsmsSoftwareIndustry) TableName() string {
	return TableNameIsmsSoftwareIndustry
}
