// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameIsmsSoftware = "isms_software"

// IsmsSoftware 工业软件主表
type IsmsSoftware struct {
	ID                   int32     `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                                                                                                                    // 自增ID
	NameZh               string    `gorm:"column:name_zh;type:varchar(200);not null;comment:软件中文名称（不含特殊符号，如：中望CAD）" json:"name_zh"`                                                                                                                 // 软件中文名称（不含特殊符号，如：中望CAD）
	NameEn               string    `gorm:"column:name_en;type:varchar(200);not null;uniqueIndex:uk_name_version,priority:1;comment:软件英文名称（不含特殊符号，如：ZWCAD）" json:"name_en"`                                                                          // 软件英文名称（不含特殊符号，如：ZWCAD）
	Version              string    `gorm:"column:version;type:varchar(100);not null;uniqueIndex:uk_name_version,priority:2;comment:版本号（统一小写，前缀v可选，如v6.2.10、6.2）" json:"version"`                                                                    // 版本号（统一小写，前缀v可选，如v6.2.10、6.2）
	ReleaseYear          *int32    `gorm:"column:release_year;type:year(4);index:idx_release_date,priority:1;comment:发布年份（如2023）" json:"release_year"`                                                                                              // 发布年份（如2023）
	ReleaseMonth         *int32    `gorm:"column:release_month;type:tinyint(3) unsigned;index:idx_release_date,priority:2;comment:发布月份（1-12，NULL表示仅精确到年）" json:"release_month"`                                                                     // 发布月份（1-12，NULL表示仅精确到年）
	ReleaseDay           *int32    `gorm:"column:release_day;type:tinyint(3) unsigned;index:idx_release_date,priority:3;comment:发布日（1-31，NULL表示仅精确到年或月）" json:"release_day"`                                                                        // 发布日（1-31，NULL表示仅精确到年或月）
	DeveloperID          int32     `gorm:"column:developer_id;type:int(10) unsigned;not null;index:idx_developer,priority:1;comment:开发商ID（关联isms_developer.id）" json:"developer_id"`                                                                // 开发商ID（关联isms_developer.id）
	CPUReq               *string   `gorm:"column:cpu_req;type:varchar(200);comment:处理器要求（如：Intel i5及以上）" json:"cpu_req"`                                                                                                                            // 处理器要求（如：Intel i5及以上）
	MemoryMinGb          *float64  `gorm:"column:memory_min_gb;type:decimal(6,2);comment:最小内存要求（GB）" json:"memory_min_gb"`                                                                                                                          // 最小内存要求（GB）
	DiskMinGb            *float64  `gorm:"column:disk_min_gb;type:decimal(6,2);comment:最小磁盘空间（GB）" json:"disk_min_gb"`                                                                                                                              // 最小磁盘空间（GB）
	SysReqOther          *string   `gorm:"column:sys_req_other;type:text;comment:其他系统要求（如显卡、网络）" json:"sys_req_other"`                                                                                                                              // 其他系统要求（如显卡、网络）
	Description          *string   `gorm:"column:description;type:text;comment:软件描述（功能、应用场景等）" json:"description"`                                                                                                                                  // 软件描述（功能、应用场景等）
	SizeBytes            *int64    `gorm:"column:size_bytes;type:bigint(20) unsigned;comment:软件实际大小（字节，用于计算和存储，1KB=1024字节）" json:"size_bytes"`                                                                                                      // 软件实际大小（字节，用于计算和存储，1KB=1024字节）
	DeploymentMethod     *string   `gorm:"column:deployment_method;type:enum('standalone','cloud','hybrid');comment:部署方式（standalone：单机；cloud：云端；hybrid：混合）" json:"deployment_method"`                                                               // 部署方式（standalone：单机；cloud：云端；hybrid：混合）
	ComplianceInfo       *string   `gorm:"column:compliance_info;type:text;comment:合规性信息（如认证标准、行业规范）" json:"compliance_info"`                                                                                                                       // 合规性信息（如认证标准、行业规范）
	SecurityInfo         *string   `gorm:"column:security_info;type:text;comment:安全信息（如加密方式、漏洞修复记录）" json:"security_info"`                                                                                                                          // 安全信息（如加密方式、漏洞修复记录）
	IntellectualProperty *string   `gorm:"column:intellectual_property;type:text;comment:知识产权信息（如专利号、著作权登记号）" json:"intellectual_property"`                                                                                                         // 知识产权信息（如专利号、著作权登记号）
	Status               string    `gorm:"column:status;type:enum('active','inactive','testing','discontinued');not null;index:idx_status,priority:1;default:active;comment:状态（active：有效；inactive：下架；testing：测试中；discontinued：停止维护）" json:"status"` // 状态（active：有效；inactive：下架；testing：测试中；discontinued：停止维护）
	CreatedAt            time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                                                                       // 创建时间
	UpdatedAt            time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                                                       // 更新时间
	BitWidths            *string   `gorm:"column:bit_widths;type:set('8bit','16bit','32bit','64bit','128bit','256bit','512bit');comment:支持的位宽集合" json:"bit_widths"`                                                                                 // 支持的位宽集合
	SourceURL            *string   `gorm:"column:source_url;type:varchar(500);comment:来源页面URL" json:"source_url"`                                                                                                                                   // 来源页面URL
	DownloadLink         *string   `gorm:"column:download_link;type:varchar(1000);comment:下载链接（种子地址等）" json:"download_link"`                                                                                                                        // 下载链接（种子地址等）
}

// TableName IsmsSoftware's table name
func (*IsmsSoftware) TableName() string {
	return TableNameIsmsSoftware
}
