// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameIsmsCountry = "isms_country"

// IsmsCountry 国家/地区表
type IsmsCountry struct {
	ID        int32     `gorm:"column:id;type:smallint(5) unsigned;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                                      // 自增ID
	NameZh    string    `gorm:"column:name_zh;type:varchar(50);not null;uniqueIndex:uk_name_zh,priority:1;comment:国家中文名称（如：中国）" json:"name_zh"`                // 国家中文名称（如：中国）
	NameEn    string    `gorm:"column:name_en;type:varchar(100);not null;comment:国家英文名称（如：China）" json:"name_en"`                                              // 国家英文名称（如：China）
	IsoCode   string    `gorm:"column:iso_code;type:char(2);not null;uniqueIndex:uk_iso_code,priority:1;comment:ISO 3166-1 alpha-2两位编码（如：CN）" json:"iso_code"` // ISO 3166-1 alpha-2两位编码（如：CN）
	Continent *string   `gorm:"column:continent;type:varchar(20);comment:所属大洲（如：亚洲、欧洲）" json:"continent"`                                                      // 所属大洲（如：亚洲、欧洲）
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                             // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                             // 更新时间
}

// TableName IsmsCountry's table name
func (*IsmsCountry) TableName() string {
	return TableNameIsmsCountry
}
