// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameIsmsSoftwareO = "isms_software_os"

// IsmsSoftwareO 软件与操作系统多对多关联表
type IsmsSoftwareO struct {
	SoftwareID int32     `gorm:"column:software_id;type:int(10) unsigned;primaryKey;comment:软件ID（关联isms_software.id）" json:"software_id"`                       // 软件ID（关联isms_software.id）
	OsID       int32     `gorm:"column:os_id;type:int(10) unsigned;primaryKey;index:idx_os,priority:1;comment:操作系统ID（关联isms_operating_system.id）" json:"os_id"` // 操作系统ID（关联isms_operating_system.id）
	Note       *string   `gorm:"column:note;type:varchar(500);comment:备注（如仅支持专业版）" json:"note"`                                                                 // 备注（如仅支持专业版）
	CreatedAt  time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:关联创建时间" json:"created_at"`                           // 关联创建时间
}

// TableName IsmsSoftwareO's table name
func (*IsmsSoftwareO) TableName() string {
	return TableNameIsmsSoftwareO
}
