// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameIsmsOS = "isms_os"

// IsmsOS 操作系统表
type IsmsOS struct {
	ID           int32     `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                                                                                         // 自增ID
	Name         string    `gorm:"column:name;type:varchar(200);not null;uniqueIndex:uk_name_version_arch,priority:1;comment:系统名称（如：Microsoft Windows、Ubuntu）" json:"name"`                                      // 系统名称（如：Microsoft Windows、Ubuntu）
	Version      string    `gorm:"column:version;type:varchar(50);not null;uniqueIndex:uk_name_version_arch,priority:2;comment:系统版本（如：7、10、20.04 LTS）" json:"version"`                                           // 系统版本（如：7、10、20.04 LTS）
	Architecture string    `gorm:"column:architecture;type:enum('x86','x64','arm32','arm64','ppc64le','s390x','riscv64');not null;uniqueIndex:uk_name_version_arch,priority:3;comment:硬件架构" json:"architecture"` // 硬件架构
	Manufacturer *string   `gorm:"column:manufacturer;type:varchar(200);comment:系统开发商（如：Microsoft、Canonical）" json:"manufacturer"`                                                                               // 系统开发商（如：Microsoft、Canonical）
	ReleaseYear  *int32    `gorm:"column:release_year;type:smallint(5) unsigned;comment:发布年份" json:"release_year"`                                                                                               // 发布年份
	Description  *string   `gorm:"column:description;type:text;comment:系统说明（如包含的细分版本）" json:"description"`                                                                                                       // 系统说明（如包含的细分版本）
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                                            // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                            // 更新时间
}

// TableName IsmsOS's table name
func (*IsmsOS) TableName() string {
	return TableNameIsmsOS
}
